### ISSUE TITLE
GHC 8.6–related mega-issue (adapting to MonadFailDesugaring)

### ISSUE THREAD

**Issue by RyanGlScott** [ekmett/lens#815]
In GHC 8.6, the `MonadFailDesugaring` extension is enabled by default. Thankfully, most libraries currently compile with this, but there are a small handful that don't. This issue is dedicated to tracking those Kmettiverse packages that don't.

* [x] `ersatz` (lib) (ekmett/ersatz#38)

  <details>

  ```
  src/Ersatz/BitChar.hs:51:8: error:
      • Could not deduce (Control.Monad.Fail.MonadFail m)
          arising from a do statement
          with the failable pattern ‘x : xs’
        from the context: (Ersatz.Problem.HasSAT s,
                           Control.Monad.State.Class.MonadState s m)
          bound by the type signature for:
                     literally :: forall s (m :: * -> *).
                                  (Ersatz.Problem.HasSAT s,
                                   Control.Monad.State.Class.MonadState s m) =>
                                  m Ersatz.Internal.Literal.Literal -> m BitChar
          at src/Ersatz/BitChar.hs:47:3-11
        Possible fix:
          add (Control.Monad.Fail.MonadFail m) to the context of
            the type signature for:
              literally :: forall s (m :: * -> *).
                           (Ersatz.Problem.HasSAT s,
                            Control.Monad.State.Class.MonadState s m) =>
                           m Ersatz.Internal.Literal.Literal -> m BitChar
      • In a stmt of a 'do' block: x : xs <- replicateM 21 (literally m)
        In the expression:
          do x : xs <- replicateM 21 (literally m)
             let x' = x && nor (take 4 xs)
                 n = Bits (reverse (x' : xs))
             return (BitChar n)
        In an equation for ‘literally’:
            literally m
              = do x : xs <- replicateM 21 (literally m)
                   let x' = ...
                       ....
                   return (BitChar n)
     |
  51 |     do x:xs <- replicateM 21 (literally m)
     |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
  </details>

* [x] `free` (`free-examples`: `exe:free-perf-th` and `exe:free-retry-th`) (ekmett/free#177)

  <details>

  ```
  PerfTH.hs:72:37: error:
      • Could not deduce (Control.Monad.Fail.MonadFail m)
          arising from a use of ‘go’
        from the context: MonadIO m
          bound by the type signature for:
                     runPerfF :: forall (m :: * -> *).
                                 MonadIO m =>
                                 [String] -> Church.F PerfF () -> m ()
          at PerfTH.hs:68:1-64
        Possible fix:
          add (Control.Monad.Fail.MonadFail m) to the context of
            the type signature for:
              runPerfF :: forall (m :: * -> *).
                          MonadIO m =>
                          [String] -> Church.F PerfF () -> m ()
      • In the first argument of ‘Church.iterM’, namely ‘go’
        In the second argument of ‘($)’, namely ‘Church.iterM go f’
        In a stmt of a 'do' block: flip runStateT ss0 $ Church.iterM go f
     |
  72 |   flip runStateT ss0 $ Church.iterM go f where
     |                                     ^^
  ```
  ```
  RetryTH.hs:76:7: error:
      • Could not deduce (Control.Monad.Fail.MonadFail m1)
          arising from a do statement
          with the failable pattern ‘Just x’
        from the context: MonadIO m
          bound by the type signature for:
                     runRetry :: forall (m :: * -> *) a. MonadIO m => Retry a -> m a
          at RetryTH.hs:56:1-39
        or from: MonadIO m1
          bound by the type signature for:
                     run :: forall (m1 :: * -> *) a1.
                            MonadIO m1 =>
                            RetryF (m1 a1) -> m1 a1
          at RetryTH.hs:59:5-43
        Possible fix:
          add (Control.Monad.Fail.MonadFail m1) to the context of
            the data constructor ‘WithRetry’
            or the type signature for:
                 run :: forall (m1 :: * -> *) a1.
                        MonadIO m1 =>
                        RetryF (m1 a1) -> m1 a1
      • In a stmt of a 'do' block:
          Just x <- runMaybeT . msum $ repeat (runRetry block)
        In the expression:
          do Just x <- runMaybeT . msum $ repeat (runRetry block)
             next x
        In an equation for ‘run’:
            run (WithRetry block next)
              = do Just x <- runMaybeT . msum $ repeat (runRetry block)
                   next x
     |
  76 |       Just x <- runMaybeT . F.msum $ repeat (runRetry block)
     |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
  </details>

* [x] `lens` (`lens-examples`: `exe:lens-pong`) (#816)

  <details>

  ```
  Pong.hs:190:3: error:
      • No instance for (Control.Monad.Fail.MonadFail Identity)
          arising from a do statement
          with the failable pattern ‘v : vs’
      • In a stmt of a 'do' block: v : vs <- use vectors
        In the expression:
          do v : vs <- use vectors
             vectors .= vs
             return v
        In an equation for ‘nextSpeed’:
            nextSpeed
              = do v : vs <- use vectors
                   vectors .= vs
                   return v
      |
  190 |   v:vs <- use vectors
      |   ^^^^^^^^^^^^^^^^^^^

  ```
  </details>

* [ ] `quine` (`exe:triangles`) (ekmett/quine#16)

  <details>

  ```
  Triangles.hs:223:3: error:
      • Could not deduce (Control.Monad.Fail.MonadFail m)
          arising from a do statement
          with the failable pattern ‘Just aColor’
        from the context: (MonadIO m, MonadState s m, HasSystem s (),
                           MonadReader e m, HasEnv e, HasOptions e)
          bound by the type signature for:
                     core :: forall (m :: * -> *) s e a.
                             (MonadIO m, MonadState s m, HasSystem s (), MonadReader e m,
                              HasEnv e, HasOptions e) =>
                             m a
          at Triangles.hs:212:1-99
        Possible fix:
          add (Control.Monad.Fail.MonadFail m) to the context of
            the type signature for:
              core :: forall (m :: * -> *) s e a.
                      (MonadIO m, MonadState s m, HasSystem s (), MonadReader e m,
                       HasEnv e, HasOptions e) =>
                      m a
      • In a stmt of a 'do' block:
          Just aColor <- attributeLocation prog "aColor"
        In the expression:
          do liftIO (getDir "shaders")
               >>= \ ss -> buildNamedStrings ss ("/shaders" </>)
             throwErrors
             liftIO $ putStrLn "compiling"
             transformVert <- compile
                                ["/shaders"] GL_VERTEX_SHADER "shaders/pass-vertex.vert"
             ....
        In an equation for ‘core’:
            core
              = do liftIO (getDir "shaders")
                     >>= \ ss -> buildNamedStrings ss ("/shaders" </>)
                   throwErrors
                   liftIO $ putStrLn "compiling"
                   ....
      |
  223 |   Just aColor    <- attributeLocation prog "aColor"
      |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
  </details>

**Comment by RyanGlScott** [comment]
These have all been addressed except for `quine` (which I do not have push access to). Since a `quine` issue really isn't under the purview of `lens`, I'll go ahead and close this in favor of ekmett/quine#16.
